# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: 'b2261634-072d-463a-9386-0c3244ca4319'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'northeurope'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/mohitsharma911/mohitsharma911/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName test'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'